### ISSUE TITLE
Getting started tasklist

### ISSUE THREAD

**Issue by mbrakken** [therabble/seattle-public-library-client#1]
- [x] Get SPL contacts & get them project access #2 
- [x] Get project name #3 
- [x] Get URL #4 
- [x] Get wildcard cert #5 
- [x] Get design standards guide #6 
- [x] Get domain name / host #7 
- [ ] Set up pre-launch placeholder site (squarespace) #8 
- [x] Create license, review with legal team #9 
- [x] Create artist FAQ #10 
- [x] Gather / create policies #11 
- [x] Get basic info about project for press & placeholder site #12

**Comment by lahollen** [comment]
@andrewharbison Check out this short guide I wrote for librarians about how to work with issues in GitHub:

https://docs.google.com/document/d/1WpF9WqztU1tOSgsLbbnpnDfEdkWxEfxLNj5AIrRmK1o/edit?usp=sharing
