### ISSUE TITLE
Submissions interface for SPL

### ISSUE THREAD

**Issue by lahollen** [therabble/seattle-public-library-client#14]
Set up MUSICat submissions interface for SPL project based on current CCR specs

**Comment by mbrakken** [comment]
@lahollen The following are dependencies I'll need in place before I can get this out. The sooner these are squared the better:

- [ ] #3 Project name
- [ ] #4 URL
- [ ] #5 Wildcard SSL cert
- [ ] #7 Domain name
- [ ] #9 License (or at least a preliminary one, so people know what they're opting in to).
- [ ] #10 Some kind of artist FAQ
- [ ] Logo?

The domain-related ones are most pertinent (domain, certs), as those block actual server configuration and deployment. The others (license, faq, logo) are somewhat dressing, but probably should be in place before any of this rolls out.

**Comment by lahollen** [comment]
@mbrakken Here are links to SPL copy in shared Google Drive:

About: https://docs.google.com/document/d/1be-V-RWbmGoaPauQZXGPnabKm0Z4LXsNpYVfgzBpUP8/edit?usp=sharing

FAQ: https://docs.google.com/document/d/1LOjPQnCwMSRIsUDsOu4iy1m5ZG8nPqAXTgqGGWSq0q0/edit?usp=sharing

Plain-language license: https://docs.google.com/document/d/160Z-QptBN0dHYC3i7qHVf_AeznH2-uX6DLuMbRAzBo8/edit?usp=sharing

/cc @prestonaustin

**Comment by prestonaustin** [comment]
Also landing page: https://docs.google.com/document/d/1WCz1RyHULisdIurRuPxcBChSJYqDNhikzMd2LEFTYys/edit
